DROP USER JOBHUNTINGDB CASCADE;

CREATE USER JOBHUNTINGDB
  IDENTIFIED BY 'JobHuntingDB123$'
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 2 Roles for JOBHUNTINGDB 
GRANT AQ_ADMINISTRATOR_ROLE TO JOBHUNTINGDB WITH ADMIN OPTION CONTAINER=ALL;
GRANT DBA TO JOBHUNTINGDB CONTAINER=ALL;
ALTER USER JOBHUNTINGDB DEFAULT ROLE ALL;

-- 8 System Privileges for JOBHUNTINGDB 
GRANT CREATE MATERIALIZED VIEW TO JOBHUNTINGDB CONTAINER=ALL;
GRANT CREATE TABLE TO JOBHUNTINGDB CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'JOBHUNTINGDB',
  ADMIN_OPTION => TRUE);
END;
/
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'JOBHUNTINGDB',
  ADMIN_OPTION => TRUE);
END;
/
GRANT GLOBAL QUERY REWRITE TO JOBHUNTINGDB CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'JOBHUNTINGDB',
  ADMIN_OPTION => TRUE);
END;
/
GRANT SELECT ANY TABLE TO JOBHUNTINGDB CONTAINER=ALL;
GRANT UNLIMITED TABLESPACE TO JOBHUNTINGDB CONTAINER=ALL;

-- 18 Object Privileges for JOBHUNTINGDB 
GRANT EXECUTE ON SYS.DBMS_AQ TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AQADM TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AQELM TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AQ_IMPORT_INTERNAL TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RULE_EXIMP TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_TRANSFORM_EXIMP TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT USE ON EDITION ORA$BASE TO JOBHUNTINGDB WITH GRANT OPTION;
GRANT EXECUTE ON SYS.SYS_GROUP TO JOBHUNTINGDB CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.X$PT5M93HIFLVR86I8UJ70SMAT5O1E TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$ACL TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$CHECKOUTS TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$CONFIG TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$D_LINK TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$H_INDEX TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$H_LINK TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$NLOCKS TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$RESCONFIG TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;
GRANT DELETE, INSERT, SELECT, UPDATE ON XDB.XDB$RESOURCE TO JOBHUNTINGDB WITH GRANT OPTION CONTAINER=ALL;

-- 1 Java Privilege for JOBHUNTINGDB 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'JOBHUNTINGDB'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => '<<ALL FILES>>'
    ,permission_action => 'read'
    ,key               => KEYNUM
    );
END;
/

-- 1 Resoure Group Privilege for JOBHUNTINGDB 
BEGIN
  SYS.DBMS_RESOURCE_MANAGER.clear_pending_area();
  SYS.DBMS_RESOURCE_MANAGER.create_pending_area();
  SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SWITCH_CONSUMER_GROUP
    ('JOBHUNTINGDB','SYS_GROUP',FALSE);
  SYS.DBMS_RESOURCE_MANAGER.submit_pending_area();
END;
/
BEGIN
  SYS.DBMS_RESOURCE_MANAGER.SET_INITIAL_CONSUMER_GROUP
    ('JOBHUNTINGDB','SYS_GROUP');
END;
/

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.CATALOG FOR SYS.CATALOG;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.COL FOR SYS.COL;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.PRODUCT_USER_PROFILE FOR JOBHUNTINGDB.SQLPLUS_PRODUCT_PROFILE;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.PUBLICSYN FOR SYS.PUBLICSYN;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.SYSCATALOG FOR SYS.SYSCATALOG;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.SYSFILES FOR SYS.SYSFILES;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.TAB FOR SYS.TAB;

CREATE OR REPLACE SYNONYM JOBHUNTINGDB.TABQUOTAS FOR SYS.TABQUOTAS;