CREATE SEQUENCE JOBHUNTINGDB.Applicants_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM APPLICANTS_SQ FOR JOBHUNTINGDB.APPLICANTS_SQ;