CREATE SEQUENCE JOBHUNTINGDB.ApplicantLanguages_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM APPLICANTLANGUAGES_SQ FOR JOBHUNTINGDB.APPLICANTLANGUAGES_SQ;