CREATE SEQUENCE JOBHUNTINGDB.ApplicantSkills_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM APPLICANTSKILLS_SQ FOR JOBHUNTINGDB.APPLICANTSKILLS_SQ;