CREATE SEQUENCE JOBHUNTINGDB.Benefits_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM BENEFITS_SQ FOR JOBHUNTINGDB.BENEFITS_SQ;