CREATE SEQUENCE JOBHUNTINGDB.Companies_sq
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM COMPANIES_SQ FOR JOBHUNTINGDB.COMPANIES_SQ;
