CREATE SEQUENCE JOBHUNTINGDB.Education_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM EDUCATION_SQ FOR JOBHUNTINGDB.EDUCATION_SQ;