CREATE SEQUENCE JOBHUNTINGDB.ExperienceTypes_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM EXPERIENCETYPES_SQ FOR JOBHUNTINGDB.EXPERIENCETYPES_SQ;