CREATE SEQUENCE JOBHUNTINGDB.HiringProcess_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM HIRINGPROCESS_SQ FOR JOBHUNTINGDB.HIRINGPROCESS_SQ;