CREATE SEQUENCE JOBHUNTINGDB.JobPositions_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM JOBPOSITIONS_SQ FOR JOBHUNTINGDB.JOBPOSITIONS_SQ;