CREATE SEQUENCE JOBHUNTINGDB.LanguageLevels_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM LANGUAGELEVELS_SQ FOR JOBHUNTINGDB.LANGUAGELEVELS_SQ;