CREATE SEQUENCE JOBHUNTINGDB.LanguageRequirements_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM LANGUAGEREQUIREMENTS_SQ FOR JOBHUNTINGDB.LANGUAGEREQUIREMENTS_SQ;