CREATE SEQUENCE JOBHUNTINGDB.LOGTABLES_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;
  
CREATE PUBLIC SYNONYM LOGTABLES_SQ FOR JOBHUNTINGDB.LOGTABLES_SQ;
