CREATE SEQUENCE JOBHUNTINGDB.ProcessStatus_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM PROCESSSTATUS_SQ FOR JOBHUNTINGDB.PROCESSSTATUS_SQ;