CREATE SEQUENCE JOBHUNTINGDB.Representatives_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM REPRESENTATIVES_SQ FOR JOBHUNTINGDB.REPRESENTATIVES_SQ;
