CREATE SEQUENCE JOBHUNTINGDB.SkillRequirements_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM SKILLREQUIREMENTS_SQ FOR JOBHUNTINGDB.SKILLREQUIREMENTS_SQ;
