CREATE SEQUENCE JOBHUNTINGDB.Skills_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM SKILLS_SQ FOR JOBHUNTINGDB.SKILLS_SQ;