CREATE SEQUENCE JOBHUNTINGDB.Titles_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE PUBLIC SYNONYM TITLES_SQ FOR JOBHUNTINGDB.TITLES_SQ;