CREATE SEQUENCE JOBHUNTINGDB.TitleRequirements_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM TITLEREQUIREMENTS_SQ FOR JOBHUNTINGDB.TITLEREQUIREMENTS_SQ;