CREATE SEQUENCE JOBHUNTINGDB.WorkExperience_SQ
  START WITH 1
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;

CREATE PUBLIC SYNONYM WORKEXPERIENCE_SQ FOR JOBHUNTINGDB.WORKEXPERIENCE_SQ;