DROP TABLE JOBHUNTINGDB.EDUCATION_TB CASCADE CONSTRAINTS;

CREATE TABLE JOBHUNTINGDB.EDUCATION_TB
(
  EDUCATIONID           NUMBER(18)              NOT NULL,
  APPLICANTID           NUMBER(18)              NOT NULL,
  STARTYEAR             NUMBER(6)               NOT NULL,
  ENDYEAR               NUMBER(6),
  TITLEID               NUMBER(18)              NOT NULL,
  DESCRIPTIONEDUCATION  VARCHAR2(200 BYTE)      NOT NULL
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON TABLE JOBHUNTINGDB.EDUCATION_TB IS 'Tabla que almacena la educacioon del aplicante';

COMMENT ON COLUMN JOBHUNTINGDB.EDUCATION_TB.EDUCATIONID IS 'Campo que almacena el codigo de educacion';

COMMENT ON COLUMN JOBHUNTINGDB.EDUCATION_TB.APPLICANTID IS 'Campo que tiene el codigo del postulante';

COMMENT ON COLUMN JOBHUNTINGDB.EDUCATION_TB.STARTYEAR IS 'Campo que almacena el anio que empezo el estudio';

COMMENT ON COLUMN JOBHUNTINGDB.EDUCATION_TB.ENDYEAR IS 'Campo que almacena el anio que finaliza el estudio';

COMMENT ON COLUMN JOBHUNTINGDB.EDUCATION_TB.TITLEID IS 'Campo que contiene el tipo de titulo';

COMMENT ON COLUMN JOBHUNTINGDB.EDUCATION_TB.DESCRIPTIONEDUCATION IS 'Campo que alamcena una breve descripcion de curso';


CREATE UNIQUE INDEX JOBHUNTINGDB.EDUCATION_TB_PK ON JOBHUNTINGDB.EDUCATION_TB
(EDUCATIONID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE JOBHUNTINGDB.EDUCATION_TB ADD (
  CONSTRAINT STARTYEAREDUCATION_CK
  CHECK (StartYear >= 0)
  ENABLE VALIDATE
,  CONSTRAINT EDUCATION_TB_PK
  PRIMARY KEY
  (EDUCATIONID)
  USING INDEX JOBHUNTINGDB.EDUCATION_TB_PK
  ENABLE VALIDATE);


ALTER TABLE JOBHUNTINGDB.EDUCATION_TB ADD (
  CONSTRAINT APPLICANTIDEDUCATION_FK 
  FOREIGN KEY (APPLICANTID) 
  REFERENCES JOBHUNTINGDB.APPLICANTS_TB (APPLICANTID)
  ENABLE VALIDATE
,  CONSTRAINT TITLEIDEDUCATION_FK 
  FOREIGN KEY (TITLEID) 
  REFERENCES JOBHUNTINGDB.TITLES_TB (TITLEID)
  ENABLE VALIDATE);


CREATE PUBLIC SYNONYM EDUCATION_TB FOR JOBHUNTINGDB.EDUCATION_TB;
