CREATE TABLE JOBHUNTINGDB.LOGTABLES_TB
(
  IDLOG      NUMBER(18)                         NOT NULL,
  TABLELOG   VARCHAR2(100)                      NOT NULL,
  DLL        VARCHAR2(100)                      NOT NULL,
  BEFORELOG  VARCHAR2(4000),
  AFTERLOG   VARCHAR2(4000),
  USERLOG    VARCHAR2(20)                       NOT NULL,
  FECLOG     DATE                               NOT NULL
);

COMMENT ON TABLE JOBHUNTINGDB.LOGTABLES_TB IS 'TABLA QUE ALMACENA LOS MOVIMEINTOS INSERT, UPDATE, DELETE EN LAS TABLAS';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.IDLOG IS 'CAMPO DE LLAVE PRIMARIA';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.TABLELOG IS 'CAMPO QUE INDICA QUE TABLA QUE AFECTO';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.DLL IS 'CAMPO QUIE INDICA SI ES UN INSERT, UPDATE, DELETE';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.BEFORELOG IS 'CAMPO QUE INIDCA COMO ESTABA ANTES';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.AFTERLOG IS 'CAMOPO QUE INDICA COMO QUEDA LUEGO DE APLICACION';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.USERLOG IS 'CAMPO QUE INIDCA USUARIO QUE APLICO MOVIMEINTO ';

COMMENT ON COLUMN JOBHUNTINGDB.LOGTABLES_TB.FECLOG IS 'CAMPO QUE INDICA LA FECHA QUE SE APLICO';


ALTER TABLE JOBHUNTINGDB.LOGTABLES_TB ADD (
  CONSTRAINT LOG_TB_PK
  PRIMARY KEY
  (IDLOG)
  ENABLE VALIDATE);

CREATE PUBLIC SYNONYM LOGTABLES_TB FOR JOBHUNTINGDB.LOGTABLES_TB;