ALTER TABLE JOBHUNTINGDB.HIRINGPROCESS_TB
 ADD (JOBPOSITIONID  NUMBER NOT NULL);


COMMENT ON COLUMN JOBHUNTINGDB.HIRINGPROCESS_TB.JOBPOSITIONID IS 'Campo que indica el job postulado';
ALTER TABLE JOBHUNTINGDB.HIRINGPROCESS_TB
 ADD CONSTRAINT HIRINGPROCESS_TB_R03 
  FOREIGN KEY (JOBPOSITIONID) 
  REFERENCES JOBHUNTINGDB.JOBPOSITIONS_TB (POSITIONID)
  ENABLE VALIDATE;