CREATE TABLE JOBHUNTINGDB.TITLEREQUIREMENTS_TB
(
  TITLEID     NUMBER(18)                        NOT NULL,
  POSITIONID  NUMBER(18)                        NOT NULL,
  DESIRABLE   NUMBER(1)                         DEFAULT 0                     NOT NULL
);

COMMENT ON TABLE JOBHUNTINGDB.TITLEREQUIREMENTS_TB IS 'Tabla que almacena los titulos que requieren las postulaciones';

COMMENT ON COLUMN JOBHUNTINGDB.TITLEREQUIREMENTS_TB.TITLEID IS 'Llave primaria y foranea para el codigo de los titulos';

COMMENT ON COLUMN JOBHUNTINGDB.TITLEREQUIREMENTS_TB.POSITIONID IS 'Llave primaria y foranea para el codigo de la potulacion';

COMMENT ON COLUMN JOBHUNTINGDB.TITLEREQUIREMENTS_TB.DESIRABLE IS 'Campo que indica si el titulo es indespensable';


ALTER TABLE JOBHUNTINGDB.TITLEREQUIREMENTS_TB ADD (
  CONSTRAINT TITLEREQUIREMENTS_TB_PK
  PRIMARY KEY
  (TITLEID,POSITIONID)
  ENABLE VALIDATE
,  CONSTRAINT DESIRABLE_CK
  CHECK (DESIRABLE IN(0,1))
  ENABLE VALIDATE);


ALTER TABLE JOBHUNTINGDB.TITLEREQUIREMENTS_TB ADD (
  CONSTRAINT TITLEIDTITLEREQUIREMENTS_FK 
  FOREIGN KEY (TITLEID) 
  REFERENCES JOBHUNTINGDB.TITLES_TB (TITLEID)
  ENABLE VALIDATE
,  CONSTRAINT POSITIONIDTITLEREQUIREMENTS_FK 
  FOREIGN KEY (POSITIONID) 
  REFERENCES JOBHUNTINGDB.JOBPOSITIONS_TB (POSITIONID)
  ENABLE VALIDATE);

CREATE PUBLIC SYNONYM TITLEREQUIREMENTS_TB FOR JOBHUNTINGDB.TITLEREQUIREMENTS_TB;